CREATE TABLE if not exists HITS
(
    --ID INTEGER PRIMARY KEY auto_increment,
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    APP VARCHAR(50) NOT NULL,
    URI VARCHAR(50) NOT NULL,
    IP  VARCHAR(19) NOT NULL,
    CREATED TIMESTAMP DEFAULT NOW()
);