version: '3.1'
services:
  stats-server:
    ports:
      - "9090:9090"
    build: ./statsmodule/stats-server
    image: binom_statserver_v1
    container_name: stats-server
    depends_on:
      - stats-db
    environment:
      - DB_HOST=stats-db
      - DB_PORT=5432
      - DB_NAME=hits
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    volumes:
        - /var/lib/postgresql/data/
    ports:
        - "6541:5432"
    environment:
        - POSTGRES_DB=hits
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root

  ewm-service:
    ports:
      - "8080:8080"
    build: ./statsmodule/stats-client
    image: binom_statclient_v1
    container_name: ewm-service
    depends_on:
      - stats-server
    environment:
      - stat-server.url=http://stats-server:9090

